### ISSUE TITLE
Focus Management

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#107]
**User Story**

A developer needs an easy way to manage focus in an application and easily move that focus.

**Discussion**

Focus management is a core bit of functionality to "get right".  Focus management in a virtual DOM though can require programatically setting focus on the real DOM node during a render.  It makes sense to consider an "abstraction" of some sort, that is integrated into the projector, that allows a focus manager to "collect" the real DOM nodes and when a widget needs to have its focus set, it would be a call to the projector with something like `setFocus(widget)` or `setFocus('widget-id')`.  Possibly this would be an `app` construct too.

Also, note that in many cases, the DOM/VDom root emitted by the widget would not be the focus node.  Therefore we will need a way identify the nodes that are the focus node for a particular widget (e.g. `data-focus-node` attribute).

**Comment by mwistrand** [comment]
So would applications be required to pass the projector around in order for widgets to receive focus when they need it? In this case, how might widgets that have specific requirements for keyboard navigation handle focus management without requiring that the application to explicitly pass in a projector instance?

**Comment by kitsonk** [comment]
I think we need to switch it around...

Why would a widget need to grab focus?  It might need to express that "if I have focus, this sub part of me should be the focus" and some sort of "if you navigated within me, here is the current ordering of my focus points".  As a widget would reveal different sub-parts, it would re-render that "meta-data".

Remember, widgets are reactive.  They respond to things.  They don't actually do anything if we can avoid it at any cost.

The management part of it would have to occur at a point where some actor has a whole view of everything going on.  Widgets shouldn't take focus, otherwise it would be chaos, like little squabbling children.

**Comment by mwistrand** [comment]
Take a look at the [WAI-ARIA menu example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html). Each menu only has top-level item with a `tabIndex` other than `-1`. As the user presses arrow keys within each item, however, focus is manually placed that specific item. A property can and should be used to determine whether a similar item in a Dojo 2 menu should receive focus, but if focus management takes place within the projector, how would the two communicate with each other?

**Comment by kitsonk** [comment]
Exactly the same the widget communicates to the projector now... by invalidating itself and then providing a different render when it is requested.

**Comment by mwistrand** [comment]
Well, yes, but it's still not clear to me how the widget communicates to the projector (focus manager) that it should receive focus. In other words, `invalidate()` by itself doesn't mitigate the need to call `element.focus()` from within `onElementUpdated`. So how would the focus manager know which of the invalidated widgets (if any) should receive focus?

**Comment by kitsonk** [comment]
That is my suggestion though that we have a reactive solution to managing focus and abstract the widget developer from the DOM.  If that means we have to express a property in our `DNode`s to affect that, that is what I would recommend.

**Comment by mwistrand** [comment]
In private conversations the question has come up whether a focus manager is even necessary. My personal view is that having a single controller for setting focus is helpful. While it cannot prevent widgets from fighting over focus like "squabbling children", it does at least provide a vehicle for warning application developers when they are. Otherwise, widget authors would have to wait for bugs to surface before learning whether their widgets are requesting focus unnecessarily. Even something as simple as the following would go a long way to help resolve focus issues:

```typescript
// list of selectors that can receive focus natively
const tabbable = [ /* ... */ ];

class FocusManager {
	private _focusScheduled = false;

	setFocus(element: HTMLElement) {
		if (this._focusScheduled) {
			console.warn('Focus already scheduled for a different DOM node.');
		}

		const focusable = this._resolveFocusableElement(element);
		if (!focusable) {
			throw new Error('Element must either have a `tabIndex` or be focusable natively.');
		}

		this._focusScheduled = true;
		requestAnimationFrame(() => {
			this._focusScheduled = false;
			focusable.focus();
		});
	}

	private _resolveFocusableElement(element: HTMLElement): HTMLElement | void {
		const tag = element.nodeName.toLowerCase();
		if (tabbable.indexOf(tag) > -1 || element.getAttribute('tabIndex')) {
			return element;
		}

		const focusableChild = element.querySelector('[data-dojo-focus-node]');
		if (focusableChild && focusableChild.getAttribute('tabIndex')) {
			return focusableChild as HTMLElement;
		}
	}
}
```

**Comment by kitsonk** [comment]
I would be 👍 for abstracting developers from touching the DOM and 👍 for adding some sort of control point to at least monitor the squabbling children!

**Comment by smhigley** [comment]
I could see a use for creating a level of abstraction between widget developers and the actual DOM node, but I'm not sure we need to try to apply logic to which element gets focus. In my opinion, focus should never be set except in direct response to a user action, ideally in an event handler. I don't see this interfering with reactive principles, since in my view focus shouldn't be directly managed in the first place.

My initial thought for a "focus manager" wasn't to manage focus exactly, but focusability. For elements that should create focus traps (dialogs, flyout menus, anything that visually interferes with the user's ability to interact with part of the page), we need something that will either set `tabindex` on focusable elements within a container, or that will listen to focus events on `document` and redirect focus when it leaves the focus trap.

**Comment by smhigley** [comment]
Playing with Menu, I think I've come up with a pattern for setting focus on child elements that works and isn't buggy (i.e. doesn't ever try to steal focus back when it shouldn't). It involves the parent widget passing the child widget a property that if true, sets focus in `onElementUpdated` and immediately calls a function also passed in to the child that reverts the focus property to false. So, for example (obviously oversimplified):

```javascript
// Menu class
private _activeIndex = 0;
private _callFocus = false;

private _onMenuItemFocusCalled() {
	this._callFocus = false;
}

private _onMenuItemKeyDown(event: KeyboardEvent) {
	if (key logic stuff to focus next menu item) {
		this._activeIndex++;
		this._callFocus = true;
	}
}

private _renderChildren(children) {
	return children.map((props, i) => w(MenuItem, {
		(... stuff),
		callFocus: this._callFocus && i === this._activeIndex,
		onKeyDown: this._onMenuItemKeyDown,
		onFocusCalled: this._onMenuItemFocusCalled
	}));
}

// MenuItem class
protected onElementUpdated(element: HTMLElement, key: string) {
	if (key === 'root') {
		const { index, callFocus, onFocusCalled } = this.properties;

		if (callFocus) {
			element.focus();
			onFocusCalled && onFocusCalled(element, index);
		}
	}
}
```

**Comment by smhigley** [comment]
New potential focus manager concern:
There are a certain widgets (e.g. dropdown menu, tooltip) that open popups that one would normally expect to close if a user clicks somewhere else on screen (or moves focus away by tabbing).

These could both be handled in something like an `onWidgetBlur` event, but we would need both dom querying (for `document.activeElement`) and a document-level focus handler. Should we add that to the list of things a focus manager should do?

**Comment by mwistrand** [comment]
There's also the limitation that elements cannot receive focus until they are completely visible, which can be problematic when the next item that should receive focus is animated into view (depending on the requirements of the animation).

**Comment by mwistrand** [comment]
I think I have an idea that might work for focus management and that shouldn't require widgets to interact directly with the DOM. We extend `VirtualDomProperties` with a `callFocus` (or just `focus`) property as well as an `onFocusCalled` property. `callFocus` would need to be able to communicate whether its own nodes should be focused, or the first available focusable node should receive focus. `onFocusCalled` would be used by parents to prevent children from trying to steal focus.

`v` (but I don't think `WidgetBase`) would need to be updated to pass its vnode to a `scheduleRender` method. `vnode.properties.afterCreate` and `vnode.properties.afterUpdate` would be wrapped with a function that calls `element.focus()`, but only if the vnode in question is supposed to receive focus.

A very basic POC is up [here](https://github.com/mwistrand/widget-core/commit/eafa15a1bd4c91ce78dcc199bcbf3806e4c7b43c) (h/t @smhigley for the "get first focusable element" selector).

**Comment by smhigley** [comment]
I'd like to propose something like a final list of requirements for the focus manager with their use cases. If there are no more additions, it'd be nice to actually start making this thing:
- Handle calling `element.focus()`
  _Use Case:_
  Abstract away touching the DOM from the current implementation in `onElementUpdated`, and handle the `callFocus`/`onFocusCalled` pattern for widget users
- Get list of focusable elements
  _Use Case:_
  When calling focus on an widget, there may be a case when we need to find the first focusable element. Even if a node is specified, we should probably check that it is focusable before attempting to call `.focus()`. This approach would also help solve the next few use cases:
- Trap focus within a widget or VNode
  _Use Case:_
  Dialog, Slidepane, and possibly other modal-ish widgets need to be focus traps. If we have a reference to all focusable nodes, we can listen to blur on the last one instead of needing a document-level focus listener.
- “unfocus” a widget or VNode
   _Use Case:_
  Any hidden component (e.g. the month popup in Calendar or a collapsed sub-menu) shouldn't be able to receive focus. While this could be achieved by removing the node or setting its css to `visibility: hidden`, both approaches hinder animation performance. It'd be nice if we could provide a way to loop through all focusable nodes and set `tabIndex: -1`.
- Widget-level focus and blur events
   _Use Case:_
   Any action or change that needs to take place when focus enters or leaves the widget as a whole, e.g. closing a tooltip or popup. The implementation should be the same as a focus trap, where we would either need to listen to focus on the document, or focus on the first focusable/blur on the last

**Comment by rishson** [comment]
@bitpshr @mwistrand @tomdye @agubler @matt-gadd comments on @smhigley 's proposal above please, so we can progress this.

**Comment by mwistrand** [comment]
@smhigley I believe that covers all of my concerns!

**Comment by smhigley** [comment]
As a quick note, the Accessibility article in dojo.io will need to be updated when this lands: https://github.com/dojo/dojo.io/pull/191#pullrequestreview-65653030

**Comment by kitsonk** [comment]
@agubler and @matt-gadd we should resolve this issue if there is any action for the next beta release.  If there isn't a concern here, we should close this issue with our reasoning why.

**Comment by matt-gadd** [comment]
@kitsonk we think this would currently be actioned in `dojo/widgets` or at least the majority of the requirements listed above. would you like to move it there?

**Comment by kitsonk** [comment]
Issue moved to [dojo/widgets #309](https://github.com/dojo/widgets/issues/309) via [**ZenHub**](https://www.zenhub.com/)
