### ISSUE TITLE
Enhance current decorator system

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widget-core#402]
**Enhancement** 
At the moment the decorator system is quite rudimentary. The decorators themselves pretty much just desugar to `this.addDecorator('name-of-decorator', args)` calls. This means for all the decorators so far we have ended up having to add code to either `WidgetBase` or a mixin on top of it for it actually to function. This kind of defeats the additive approach of decorators, and hits us with other limitations like not being able to build decorators that compose others currently.

To have a more flexible decorator system, we should take a look at creating a more defined api for registering decorators - potentially picking a number of hook points/phases that they can attach to in WidgetBase (`afterRender`, `beforeProperties` etc). As well as looking at how we can compose decorators to create behaviour that builds on top.

**Comment by agubler** [comment]
The initial change is to update the way in which the decorators are added programatically; the consumer would no longer call `this.addDecorator('decoratorKey', value)` but directory invoke the decorator function itself in the constructor `diffProperty('store', DiffType.REFERENCE)(this);`. Existing decorators that currently do not accept an argument such as `afterRender` will be updated to factory decorators and use the `function` argument if passed (otherwise look for the function on the target instance).

Using decorators:

```ts
@afterRender(MyExternalFunction)
class MyWidget extends WidgetBase<WidgetProperties> {

    @afterRender()
     afterRenderForTargetFunction() {}
}
```

Using programmatic API:

```ts
class MyWidget extends WidgetBase<WidgetProperties> {

    constructor() {
        super();
        afterRender()(this, 'afterRenderForTargetFuncton');
        afterRender(MyExternalFunction)(this);
     }

     afterRenderForTargetFunction() {}
}
```

This will facilitate the capability to compose decorators programmatically and within a decorator environment.

```ts
function myCustomDecorator(target) {
    const customStuff = (dNode: DNode) => {
        // do things
        return w('div', [ 'special node' ]);
    }
    afterRender(customStuff)(target);
}
```

Lastly possibly provide a DecoratorMixin that will abstract the user away from needing at manually add them when authoring widgets. Maybe only be able to support this for class level decorators.

```ts
export function DecoratorMixin<T extends Constructor<WidgetBase<any>>>(Base: T, decorators: Function[]): T {
	class Decorator extends Base {
	    constructor() {
                decorators.forEach((decorator) => {
                    decorator(this);
                });
            }
        };
	return Decorator;
}

export default DecoratorMixin;
```

```ts
const decorators = [
    afterRender(CustomFunction),
    diffProperty('myProperty', DiffType.REFERENCE)
];

const MyWidgetBase = DecoratorMixin(WidgetBase, decorators);

class MyWidget extends MyWidgetBase<Properties> {
    // things
}
```
