### ISSUE TITLE
Make the Projector append sync

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widget-core#427]
At the moment the projector append returns a Promise, but in fact under the hood everything is appended sync anyway. Given its unlikely (and likely undesirable) to do this actually async in the future, for simplicity we should just remove returning a promise from append. This would likely clean up code in the projector, while also cleaning up a lot of our tests that use it.

**Comment by kitsonk** [comment]
Yeah, I can't think of a reason why we would maintain that.  I makes things awkward.

**Comment by kitsonk** [comment]
Originally, we created the attachment as an async return, because while the attachment via maquette was sync, the early iteration of the system often wouldn't be in a state of properly rendering within that initial turn.  As their state changes happened out of turn, you would often get a widget that would render nothing until other items happened during the turn.

Because the newer widgets are more "push" than "pull", they are in a situation of properly rendering in turn.  Therefore we don't have to wait for a subsequent render to be scheduled to ensure that the attached vdom is "correct".
