### ISSUE TITLE
Extend `w` to be symmetrical with `v`

### ISSUE THREAD

**Issue by agubler** [dojo/widget-core#439]
**Enhancement** 

For `v` the `properties` argument is optional and can be excluded if there are no attributes required for the `HNode`, however `w` does not mirror this API. We should extend `w` to make the `properties` argument optional and deal with children if they are passed as the second argument, such that the following are all valid.

```ts
w(WidgetBase);
w('widget');
w(WidgetBase, { key: 'key' });
w('widget', { key: 'key' });
w(WidgetBase, [ w(WidgetBase), 'child', null ]);
w('widget', [ w(WidgetBase), 'child', null ]);
w(WidgetBase, { key: 'key' }, [ w(WidgetBase), 'child', null ]);
w('widget', { key: 'key' }, [ w(WidgetBase), 'child', null ]);
```

**Comment by kitsonk** [comment]
I have also noticed on the `HNode` interface that `.children` are not optional but on `WNode` they are, but I think looking at the implementations of `v()` and `w()` they are actually both optional.

Also, on the `HNode` the `.children` is of type `(DNode | string)[]` where `string` is redundant because it is already part of `DNode`.

**Comment by agubler** [comment]
I actually think that they are both `mandatory` on the `HNode` and `WNode` interfaces (or at least should be) - they are optional in the `v()` and `w()` which should default the `children` to an empty array.

**Comment by kitsonk** [comment]
👍  to both being mandatory and should be created as empty arrays if not passed
