### ISSUE TITLE
State Injection Comments

### ISSUE THREAD

**Issue by edhager** [dojo/widget-core#495]
I was reading the widget-core readme and I have comments and questions about the state injection classes and functions.

```
registry.define('state', Injector(BaseInjector, myStateContext));
```
Why do we need the `Injector` mixin when we have `BaseInjector`?  Couldn't `BaseInjector` implement the `render` method and people could subclass `BaseInjector` when they want to add custom behavior?  The above line would become

```
registry.define('state', new BaseInjector(myStateContext));
```
The `InjectorProperties` interface is really confusing without looking at the implementation.  Looking at just the README, it is impossible to decipher. 

```
beforeRender(renderFunc: () => DNode, properties: any, children: any): DNode {
	return () => {
		return w('state', {
			render: renderFunc,
			getProperties(context: any, properties: any): any {
				return context;
			},
			properties,
			getChildren(context: any, children: DNode[]): DNode[] {
				return [];
			},
			children
		});
	};
}
```

When I look at the code above, I asked myself, why am I required to create getters for `properties` and `children` but then I have to pass them as object properties as well.  Can we remove the need to set the `properties` and `children`properties in the `InjectorProperties` and just require the getter methods?

**Comment by agubler** [comment]
The registry does not manage instances, it manages classes. This is why we use a mixin to "inject" the context to the class itself. So the following does not allow for the context to be injected and therefore available when the widgeting system creates an instance of the injector.

```ts
registry.define('state', BaseInjector);
```

> The InjectorProperties interface is really confusing without looking at the implementation. Looking at just the README, it is impossible to decipher.

Perhaps we need to add better API documentation or maybe even consider the naming. 

> When I look at the code above, I asked myself, why am I required to create getters for `properties` and `children` but then I have to pass them as object properties as well. Can we remove the need to set the `properties` and `children` properties in the `InjectorProperties` and just require the getter methods?

We can't because we need a reference to the `properties` and `children` in order to "decorate" them with the injected properties. 

The `children` and `properties` properties are the original references from the widget instance. The functions `getChildren` and `getProperties` are called by the `Injector` to determine what to values to mix over or append to these original references.

**Comment by agubler** [comment]
@edhager I hope that this helped answer some of your questions 👍 I am going to close the discussion issue now, but please re-open if you have any other questions.
