### ISSUE TITLE
Setting the "initial state" based on this properties

### ISSUE THREAD

**Issue by sebilasse** [dojo/widget-core#611]
First of all the question :
When I need to set the initial state for any widget when it is rendered the first time (e.g. serverside)
I would need a method which is _not_ invoked in any subsequent render, something like "beforeFirstRender".
What is the correct way to set the state based on `this.properties` which comes from "outside" ?

Let me describe :
@agubler made a wonderful example to demonstrate https://github.com/dojo/widget-core/issues/609 and I am thankful.
Now my semantic ui modules (like Accordion, Tab etc.) are working fine except when I need to set a class based on properties.
Made a fork of the example to demonstrate what I mean, see
--> https://github.com/sebilasse/adding-class 

In src/App the line 94 is the problem below the "TODO FIXME" comment ...

**Comment by agubler** [comment]
@sebilasse sorry about the delay getting back to you.

Personally I would look to invert the control of the active state outside of the Accordion so that it is directly controlled with the panel configuration and that the consumer needs to pass in a function that deals with a panel being selected.

That said it is also possible to do something using a "default" active configuration and setting an attribute to determine if the widget been initialised and using the default appropriately.

I've pushed up two branches, showing an example for each approach:

Using a default active configuration: https://github.com/agubler/adding-class/tree/seb-defaults
Inverting control to the parent (in this case `App.ts`): https://github.com/agubler/adding-class/tree/seb-inverting-control

**Comment by agubler** [comment]
@sebilasse is this resolved now?

**Comment by sebilasse** [comment]
@agubler Yes. Resolved. This can be closed.

**Comment by agubler** [comment]
Thanks @sebilasse, I hope you got to a solution that you are happy with.

**Comment by sebilasse** [comment]
Yes, seb-defaults is exactly what I was looking for.
