### ISSUE TITLE
Can't use meta

### ISSUE THREAD

**Issue by sebilasse** [dojo/widget-core#626]
just updated to use meta for draggable and resizable modules

When I want to import it

```
ERROR in ./src/lib/main.ts
Module not found: Error: Can't resolve '@dojo/widget-core/meta/Base' in '/Users/sebi/Desktop/redaktorTS2/src/webcomponents/semantic/src/lib'
 @ ./src/lib/main.ts 42:13-51
 @ ./src/widgets/Container/Resizable.ts
 @ ./src/App.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client? ./src/main.css ./src/main.ts
```

But the path and contents is fine
```
import { WidgetBase } from '@dojo/widget-core/WidgetBase';
import MetaBase from '@dojo/widget-core/meta/Base';
```

it imports WidgetBase but NOT MetaBase (?)

Apart from that I can't write `this.meta` anywhere because dojo build says it is undefined.

**Comment by matt-gadd** [comment]
hi @sebilasse, can you run `npm list @dojo/widget-core` in the root of your project and confirm what version you have installed? we shipped `meta` in `2.0.0-beta2.4` so you will need that version or above of widget-core.

**Comment by sebilasse** [comment]
@matt-gadd  Upps.
`sebi$` `npm list @dojo/widget-core`

```
semantic@1.0.0 /Users/sebi/Desktop/redaktorTS2/src/webcomponents/semantic
└── @dojo/widget-core@2.0.0-beta2.3  extraneous

npm ERR! extraneous: @dojo/widget-core@2.0.0-beta2.3 /Users/sebi/Desktop/redaktorTS2/src/webcomponents/semantic/node_modules/@dojo/widget-core
```

with `"@dojo/widget-core": "next"` in the package.json

**Comment by kitsonk** [comment]
Welcome to npm 5.

You should try to remove the `node_modules` and the `package-lock.json` and re-install.

In addition you will need to go back to npm 4 or upgrade to npm 5.3.0 or later.

**Comment by sebilasse** [comment]
@kitsonk Thankyou. I thought it is related to continuous npm adventures (already updated to 5.3.0 and deleted node_modules but didn't have the guts to delete this -lock.json).
Just did it, from here it is works like a charm now ;)

**Comment by kitsonk** [comment]
It would need to be longer than that (and npm3 and npm4 work fine) and even then, our testing indicates that npm doesn't even really mention anything about it.  Even if you had 5.3.0, it is likely at some point the `package-lock.json` would have been written for your downstream project and would have locked you in that version.  Part of the problem is being on a tag instead of a proper semver too.  There are just challenges with npm5, that everyone is struggling with.

Since this is resolved for now, I am going to close.
