### ISSUE TITLE
Use Benchmark.js to hook into lighthouse/puppeteer to extract first paint metrics

### ISSUE THREAD

**Issue by umaar** [dojo/widget-core#698]
Extract the first paint metrics of Dojo 2 widget-core and report that into the test harness so that we understand performance changes internally.

This would be useful for a post Intern 4.0 release!

**Comment by matt-gadd** [comment]
I’m not convinced first paint metrics have much validity in widget-core, given the time taken to first paint is mostly around the critical path of network resources, script parsing and evaluation etc, which widget-core isn’t responsible for. 

Benchmarking time to first meaningful paint and more crucially time to interaction would make sense in the dojo/examples repo which has real apps that holistically test our full toolchain though 👍. In the future dojo/cli-build-webpack could potentially cover parts of those performance scenarios too (but we don’t currently have any integration tests there).

In the case of widget-core performance I think we should definitely look into integrating uibench or js-framework-benchmark into our ci, I believe @agubler already has an impl of one and it just needs integrating?

**Comment by kitsonk** [comment]
What likely makes sense for widget-core are some `__render__()` baselines so we can track performance. We should have some widgets that use all the features of the widget-core, like themes, after render, etc. We should only knowingly commit code the slows that process knowingly. Doing our part to make it easier. We could also benchmark maquette so we know if upstream changes effect our code, but that is tangential and protectionist.

**Comment by agubler** [comment]
I would agree that running benchmarks for tests similar to [js-framework-benchmark](https://github.com/krausest/js-framework-benchmark) against widget-core would be beneficial. Even better would be, if these benchmarks were integrated into the CI pipeline so we can understand performance implications of proposed changes as part of the review process.

We could hook our examples up to report on metrics like first meaningful paint and first meaningful interaction, it would potentially highlight regressions but the issue is that is is as much about the application design, performance patterns like PRPL, SSR, HTTP2, service workers and possibly build tooling than really actual underlying view framework i.e. widget-core. I guess it could help us identify where "something" has changed for those examples, be that in the build command or a change of application design etc.

We should certainly tackle the first of these in widget-core and then see what makes sense for benchmarking more holistic performance metrics.

**Comment by matt-gadd** [comment]
@kitsonk yes, thats what js-framework-benchmark effectively asserts (and defacto standard so implementations with most frameworks for comparison). do we want to go ahead and move this issue to `dojo/examples`? and raise another issue here for integrating js-framework-benchmark?

**Comment by kitsonk** [comment]
Issue moved to [dojo/examples #240](https://github.com/dojo/examples/issues/240) via [**ZenHub**](https://www.zenhub.com/)
