### ISSUE TITLE
Provide beforeInit lifecycle hook

### ISSUE THREAD

**Issue by economatics** [dojo/widget-core#869]
The currently provided onAttach lifecycle hook is fired after first rendering. It would be useful in various use cases to have an event fired before first rendering. Please provide an additional hook for that purpose.

**Comment by agubler** [comment]
@economatics what is the purpose for a hook on if a widget _might_ render? 

This feels like it could cause more issues than it solves and I don’t think its something that we are likely to support without a very good reason to do so.

**Comment by economatics** [comment]
Hi @agubler, thanx for attending this issue :)

To be more precise, it would be nice to have an access to widget's properties before initial rendering occurs. A use case may be to provide default properties on widgets that have a more dynamic props type with optional attributes, like a table where data and config params are provided within props. 

Another use case may be to trigger an event to business logic layer, so that data can be fetched from REST service when properties are not yet set. A provided default prop while fetching may indicate a loading state in the meantime.

These are issues that may only be handled once, on initialization phase of a widget. Solving these within already existing @beforeProperties decorator may lead to necessarily checks whether the widget was already initialized before. So a widget has to provide an internal, boolean control switch and with that it has to serve as its own state machine. To me that is not that good cohesion. GUI logic may be mixed with infrastructural controlling behavior. 

It may not be that hard to integrate an @beforeInit decorator that is similar to @beforeProperties but is just executed once on the very beginning of __setProperties__

__setProperties__ than had just to be aware of WidgetBase's internal _initialProperties flag before calling registered @beforeInit decorators.

Wouldn't that be nice? :)

What do you think?

**Comment by krezovic** [comment]
I'm in need of something similar, for the very same reasons.

**Comment by agubler** [comment]
There is isn’t a lifecycle hook for this and I don’t think that adding another lifecycle hook is necessarily the answer. 

For providing default properties, this can be easily achieved by calling a util function in `render()` or by simply destructering with defaults.

```ts
protected render() {
    const { a = 'default', b = 'next-default' } = this.properties;
    // rest of the render function
}
```
or 

```ts
const getPropertyDefaults = (props) => {
    return { a: 'default', b: 'default', ...props };
}

protected render() {
    const { a, b } = getPropertyDefaults(this.properties);
    // rest of the render function
}
```

As for triggering side affects within a widget, generally there is no reason to couple this to a lifecycle hook, if the widget is driven by properties then it is totally possible to call a side affect function based on whether the property for the data exists by leveraging a diff property reaction.

```ts
@diffProperty('data', auto)
protected onDataChange(previous: MyProperties, current: MyProperties): void {
    const { data, fetchData } = current;
    data === undefined && fetchData && fetchData();
}
```

Advantages of this is it maintains reactivity, so that if there the data becomes undefined again, then the widget will refetch the data again.

However, If the widget is completely self contained (i.e. receives no properties) then it is also possible to leverage the existing `onAttach` lifecycle hook to perform a side affect action. Note that calling something like `fetch` directly from within a can be problematic and it is generally better to inject a function for this from an external source.

```ts
class MyWidget extends WidgetBase {

    private _myWidgetData: MyData[] | undefined;

    protected async onAttach() {
        const response = await fetch('https://my-remote-resource');
        this._myWidgetData = await response.json();
        this.invalidate();
    }

    protected render() {
        if (this._myWidgetData === undefined) {
            return v('div', [ 'Widget Is Loading!!' ]);
        }
        return v('div', [
            v('ul', this._myWidgetData.map((widgetData) => v('li', [ widgetData.value ]))
        ]);
    }
}
```

**Comment by matt-gadd** [comment]
I think we can close this given the answer above, we generally discourage the use of lifecycle hooks and it's possible to deal with the above scenario as a `default` state, which is a superset of an `init` state anyway.
